//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RxWrappers.WinFormsClient.PrimesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:dm:demos", ConfigurationName="PrimesService.IPrimesService")]
    public interface IPrimesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:dm:demos/IPrimesService/GetPrimes", ReplyAction="urn:dm:demos/IPrimesService/GetPrimesResponse")]
        int[] GetPrimes(string s);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:dm:demos/IPrimesService/GetPrimes", ReplyAction="urn:dm:demos/IPrimesService/GetPrimesResponse")]
        System.IAsyncResult BeginGetPrimes(string s, System.AsyncCallback callback, object asyncState);
        
        int[] EndGetPrimes(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrimesServiceChannel : RxWrappers.WinFormsClient.PrimesService.IPrimesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPrimesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPrimesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrimesServiceClient : System.ServiceModel.ClientBase<RxWrappers.WinFormsClient.PrimesService.IPrimesService>, RxWrappers.WinFormsClient.PrimesService.IPrimesService {
        
        private BeginOperationDelegate onBeginGetPrimesDelegate;
        
        private EndOperationDelegate onEndGetPrimesDelegate;
        
        private System.Threading.SendOrPostCallback onGetPrimesCompletedDelegate;
        
        public PrimesServiceClient() {
        }
        
        public PrimesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrimesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrimesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrimesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetPrimesCompletedEventArgs> GetPrimesCompleted;
        
        public int[] GetPrimes(string s) {
            return base.Channel.GetPrimes(s);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetPrimes(string s, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPrimes(s, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int[] EndGetPrimes(System.IAsyncResult result) {
            return base.Channel.EndGetPrimes(result);
        }
        
        private System.IAsyncResult OnBeginGetPrimes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string s = ((string)(inValues[0]));
            return this.BeginGetPrimes(s, callback, asyncState);
        }
        
        private object[] OnEndGetPrimes(System.IAsyncResult result) {
            int[] retVal = this.EndGetPrimes(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPrimesCompleted(object state) {
            if ((this.GetPrimesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPrimesCompleted(this, new GetPrimesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPrimesAsync(string s) {
            this.GetPrimesAsync(s, null);
        }
        
        public void GetPrimesAsync(string s, object userState) {
            if ((this.onBeginGetPrimesDelegate == null)) {
                this.onBeginGetPrimesDelegate = new BeginOperationDelegate(this.OnBeginGetPrimes);
            }
            if ((this.onEndGetPrimesDelegate == null)) {
                this.onEndGetPrimesDelegate = new EndOperationDelegate(this.OnEndGetPrimes);
            }
            if ((this.onGetPrimesCompletedDelegate == null)) {
                this.onGetPrimesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPrimesCompleted);
            }
            base.InvokeAsync(this.onBeginGetPrimesDelegate, new object[] {
                        s}, this.onEndGetPrimesDelegate, this.onGetPrimesCompletedDelegate, userState);
        }
    }
}
